server.port=8086
spring.application.name=board-backend

board.rabbitmq.relay-host=${RABBITMQ_STOMP_HOST:localhost}
board.rabbitmq.relay-port=${RABBITMQ_STOMP_PORT:61613}
board.rabbitmq.client-login=${RABBITMQ_STOMP_CLIENT_LOGIN:guest}
board.rabbitmq.client-passcode=${RABBITMQ_STOMP_CLIENT_PASSCODE:guest}
board.rabbitmq.system-login=${RABBITMQ_STOMP_SYSTEM_LOGIN:guest}
board.rabbitmq.system-passcode=${RABBITMQ_STOMP_SYSTEM_PASSCODE:guest}
board.rabbitmq.virtual-host=${RABBITMQ_STOMP_VHOST:/}
board.rabbitmq.auto-startup=${BOARD_RABBITMQ_AUTO_STARTUP:true}
